### ISSUE TITLE
[BUG] Applications list seems to be broken in Ubuntu 20.04

### ISSUE THREAD

**Issue by f-z-f** [home-sweet-gnome/dash-to-panel#1147]
Linux version: Ubuntu 20.04 x64
Gnome-Shell 3.36.4
Dash-To-Panel version 9999 from ubuntu's repo.

When opening applications menu ( doesn't matter if via click on button on panel or via hotkey) all opened windows become unclickable, sidebar with desktops shows as empty and only way to fix this is by logout or restarting gnome shell. If i disable extension in gnome tweaks everything works fine.

Logs:
JS ERROR: TypeError: this._updateWorkspacesFullGeometry is not a function
_newUpdateWorkspacesViews@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:464:14
show@resource:///org/gnome/shell/ui/workspacesView.js:613:14
show@resource:///org/gnome/shell/ui/viewSelector.js:276:33
_animateVisible@resource:///org/gnome/shell/ui/overview.js:580:27
show@resource:///org/gnome/shell/ui/overview.js:566:14
_toggleAppsPage@resource:///org/gnome/shell/ui/viewSelector.js:266:23

JS ERROR: TypeError: area is null
padArea@resource:///org/gnome/shell/ui/workspace.js:1101:9
_updateWindowPositions@resource:///org/gnome/shell/ui/workspace.js:1334:20
_realRecalculateWindowPositions@resource:///org/gnome/shell/ui/workspace.js:1311:14
_recalculateWindowPositions/this._positionWindowsId<@resource:///org/gnome/shell/ui/workspace.js:1286:18

![Снимок экрана от 2020-08-20 00-46-12](https://user-images.githubusercontent.com/4782269/90692907-9910e780-e27e-11ea-9b74-1c92da0363bc.png)

**Comment by f-z-f** [comment]
Founded that this was fixed by @charlesg99 ( thanks!) in v38
Package in ubuntu's repo needs update.

**Comment by trifrasite** [comment]
the issue persists on my system. could anybody pls guide me through how to get the update on my ubuntu 20.04? `sudo apt update` didnt do the trick

**Comment by michbeckii** [comment]
This problem started on my side after installing the latest update by apt. Everything worked fine beforehand. Could someone please link the pull request or provide any other guidance on how to install the fix?

**Comment by jderose9** [comment]
Don't install through ubuntu, install through github or extensions.gnome.org. The ubuntu package is pinned to an old version and GNOME broke backward compatibility.

https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation

**Comment by khireddine10** [comment]
I have also the same problem, I can't navigate through the apps, the sidebar is crashed and doesn't respond I can't click any of these apps or I can't also shut down except using the computer button.
