### ISSUE TITLE
Latest update spams syslog on 18.04

### ISSUE THREAD

**Issue by sokai** [home-sweet-gnome/dash-to-panel#1211]
Hey,

on my Ubuntu 18.04 I installed the current update to `v40` and my `/var/log/syslog` now is filled up with the following messages:
```text
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:49 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:50 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:50 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:50 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:50 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:50 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:50 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:54 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:54 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:55 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:55 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:59 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:43:59 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:44:00 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:44:00 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:44:02 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:44:02 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:44:02 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:44:02 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:44:03 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:44:03 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:44:03 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:44:03 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:44:04 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:44:04 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:44:13 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:44:13 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:44:14 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab8e6e0/StDrawingArea which isn't a descendent of the stage!
Oct 12 23:44:14 ubuntu1804 gnome-shell[3010]: Spurious clutter_actor_allocate called for actor 0x563eaab90c50/StDrawingArea which isn't a descendent of the stage!
```
I can reproduce that behaviour by dis- and enabling the extension. :-[

Thanks in advance for fixing and respect for your work!

**Comment by craigacgomez** [comment]
I have a similar logspam.
`
Oct 18 10:09:47 ZEN2 gnome-shell[1907]: Spurious clutter_actor_allocate called for actor 0x55be027523f0/Gjs_ui_panel_PanelCorner which isn't a descendent of the stage!
Oct 18 10:09:47 ZEN2 gnome-shell[1907]: Spurious clutter_actor_allocate called for actor 0x55be02753880/Gjs_ui_panel_PanelCorner which isn't a descendent of the stage!
Oct 18 10:09:47 ZEN2 gnome-shell[1907]: Spurious clutter_actor_allocate called for actor 0x55be027523f0/Gjs_ui_panel_PanelCorner which isn't a descendent of the stage!
Oct 18 10:09:47 ZEN2 gnome-shell[1907]: Spurious clutter_actor_allocate called for actor 0x55be02753880/Gjs_ui_panel_PanelCorner which isn't a descendent of the stage!
Oct 18 10:09:47 ZEN2 gnome-shell[1907]: Spurious clutter_actor_allocate called for actor 0x55be027523f0/Gjs_ui_panel_PanelCorner which isn't a descendent of the stage!
Oct 18 10:09:47 ZEN2 gnome-shell[1907]: Spurious clutter_actor_allocate called for actor 0x55be02753880/Gjs_ui_panel_PanelCorner which isn't a descendent of the stage!
Oct 18 10:09:47 ZEN2 gnome-shell[1907]: Spurious clutter_actor_allocate called for actor 0x55be027523f0/Gjs_ui_panel_PanelCorner which isn't a descendent of the stage!
Oct 18 10:09:47 ZEN2 gnome-shell[1907]: Spurious clutter_actor_allocate called for actor 0x55be02753880/Gjs_ui_panel_PanelCorner which isn't a descendent of the stage!
Oct 18 10:09:47 ZEN2 gnome-shell[1907]: Can't update stage views actor StWidget is on because it needs an allocation.
`

I also noticed that when the extension is loaded, I get the following warning
`
Oct 18 10:10:03 ZEN2 gnome-shell[1907]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
Oct 18 10:10:03 ZEN2 gnome-shell[1907]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
Oct 18 10:10:03 ZEN2 gnome-shell[1907]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
Oct 18 10:10:03 ZEN2 gnome-shell[1907]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
Oct 18 10:10:03 ZEN2 gnome-shell[1907]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
Oct 18 10:10:03 ZEN2 gnome-shell[1907]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
Oct 18 10:10:03 ZEN2 gnome-shell[1907]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
`

**System Information:**
OS: ArchLinux
Desktop Environment: Gnome 3.38.1
Kernel: Stable 5.9.1
Dash To Panel Extension Version: 40 (53f941f90887135312ac7f4316a15c166f5216f4) [git build]

**Comment by charlesg99** [comment]
Thanks guys, this should now be fixed on the master branch!

**Comment by craigacgomez** [comment]
Thanks @charlesg99 
Confirming that Dash to Panel version 40 (faf2ca26b9f832065ba56fa249828d87895a4eef) resolves this issue for me.

**Comment by DickSteelOy** [comment]
I would like to inform that this problem persists with a wayland session.

**Comment by GaVenga** [comment]
Latest update (Dash to Panel version 40 Master) spams journalctl.log in Manjaro Gnome / testing, Gnome-shell 1:3.38.1-1
.
I would like to inform that this problem persists in Xorg AND Wayland- sessions.
................................
gnome-shell: Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel_TaskbarAppIcon is on because it needs an allocation.
 gnome-shell: Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel_TaskbarAppIcon is on because it needs an allocation.
gnome-shell: Can't update stage views actor dashtopanelScrollview is on because it needs an allocation.
gnome-shell: Can't update stage views actor dashtopanelTaskbar is on because it needs an allocation.
gnome-shell: Can't update stage views actor panel is on because it needs an allocation.
gnome-shell: Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel-Panel is on because it needs an allocation.
gnome-shell: Can't update stage views actor panelBox is on because it needs an allocation.
gnome-shell: Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel_TaskbarAppIcon is on because it needs an allocation.
gnome-shell: Can't update stage views actor dashtopanelScrollview is on because it needs an allocation.
gnome-shell: Can't update stage views actor dashtopanelTaskbar is on because it needs an allocation.
................................
and so on

**Comment by homomodern** [comment]
> Latest update (Dash to Panel version 40 Master) spams journalctl.log in Manjaro Gnome / testing, Gnome-shell 1:3.38.1-1
> .
> I would like to inform that this problem persists in Xorg AND Wayland- sessions.
> ................................
> gnome-shell: Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel_TaskbarAppIcon is on because it needs an allocation.
> gnome-shell: Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel_TaskbarAppIcon is on because it needs an allocation.
> gnome-shell: Can't update stage views actor dashtopanelScrollview is on because it needs an allocation.
> gnome-shell: Can't update stage views actor dashtopanelTaskbar is on because it needs an allocation.
> gnome-shell: Can't update stage views actor panel is on because it needs an allocation.
> gnome-shell: Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel-Panel is on because it needs an allocation.
> gnome-shell: Can't update stage views actor panelBox is on because it needs an allocation.
> gnome-shell: Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel_TaskbarAppIcon is on because it needs an allocation.
> gnome-shell: Can't update stage views actor dashtopanelScrollview is on because it needs an allocation.
> gnome-shell: Can't update stage views actor dashtopanelTaskbar is on because it needs an allocation.
> ................................
> and so on


I'm sorry to bother, but this issue still persists. Is there any solution for this?
```
янв 19 19:29:59 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:29:59 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:29:59 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:29:59 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:29:59 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:29:59 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:29:59 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:29:59 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:29:59 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:29:59 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:29:59 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:29:59 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:29:59 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:29:59 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:29:59 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:29:59 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:30:03 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:30:03 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:30:03 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:30:03 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:30:03 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:30:03 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:30:03 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:30:03 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:30:03 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:30:03 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:30:03 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:30:03 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:30:03 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:30:03 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:30:03 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2
янв 19 19:30:03 eugene-laptop gnome-shell[1740]: JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js 354]: Too many arguments to method Clutter.Actor.allocate: expected 1, got 2

```

**Comment by katasta** [comment]
Same to me

> gnome-shell[1552]: Spurious clutter_actor_allocate called for actor 0x555738521d90/Gjs_ui_panel_PanelCorner which isn't a descendent of the stage!

the whole time on wayland manjaro 3.38.3 (in the meantime i am stressed at all. So many areas to configure Fonts, appearance, arc, pop shell, unite, color, shell. I have lost track and am about to leave. Sorry.

**Comment by aerogt3** [comment]
I'm also getting this, using v40 on gnome 3.28.2. Last night it resulted in 16GB /var/log/syslog file which crashed the system, haha.

> Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089af70/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089bbd0/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089af70/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089bbd0/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089af70/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089bbd0/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089af70/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089bbd0/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089af70/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089bbd0/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089af70/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089bbd0/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089af70/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089bbd0/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089af70/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089bbd0/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089af70/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089bbd0/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089af70/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089bbd0/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089af70/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089bbd0/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089af70/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089bbd0/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089af70/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:25 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089bbd0/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:26 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089af70/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:26 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089bbd0/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:39 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089af70/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:39 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089bbd0/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:46 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089af70/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:46 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089bbd0/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:58 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089af70/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:58 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089bbd0/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:58 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089af70/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:58 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089bbd0/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:58 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089af70/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:58 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089bbd0/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:58 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089af70/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:58 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089bbd0/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:59 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089af70/StDrawingArea which isn't a descendent of the stage!
Feb 15 12:23:59 robert-laptop gnome-shell[2152]: Spurious clutter_actor_allocate called for actor 0x55916089bbd0/StDrawingArea which isn't a descendent of the stage!

**Comment by Razer0123** [comment]
Still having the same issue even on gnome 40

**Comment by digitaltopo** [comment]
Seeing it in Gnome 43.4 with Wayland as well
