### ISSUE TITLE
GNOME 40 Overview Trasition Snap

### ISSUE THREAD

**Issue by PHLAK** [home-sweet-gnome/dash-to-panel#1338]
**Describe the bug**

With Dash to Panel enabled in GNOME 40 during the overview transition _out_ animation (by hitting <kbd>Super</kbd> or three finger swipe down gesture) the desktop scales like normal until nearly full screen then, at the last second, "snaps" to full screen. This is less noticeable with faster animations but is still jarring. It would be nice if this animation could be smooth all the way to the edges of the screen.

This seems to be caused by a "phantom" top bar. The shell animation doesn't take it's removal into effect. Therefor it transitions to the point it would be "full screen" _with the top bar_ then snaps to full screen for the very last frame of the animation.

**Linux distribution and version**

Arch Linux

**GNOME Shell version**

40.1

**Dash-to-Panel version**

Installed from `master` branch

**Where was Dash-to-Panel installed from?**

https://github.com/home-sweet-gnome/dash-to-panel

**Screenshots / Video captures**

[Here's a video](https://www.youtube.com/watch?v=CnVgvSQ2yYM) of the problem. I've slowed animations down using the Impatience extension so you can better see the issue.

For comparison [here is another video](https://www.youtube.com/watch?v=MMU4xnFbCic) showing the same action performed with Dash to Panel disabled.

**Comment by jderose9** [comment]
I think this is probably related to issue #1327.

I think it may be related to this code but I got stuck/ran out of time trying to override the code and reallocate everything:
https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/overviewControls.js#L50

Basically, it assumes the dash is at the top of the screen and draws some elements too low. You will notice if you put the panel at the top then the animation appears correctly.

**Comment by j-james** [comment]
I can also reproduce this on the same setup as PHLAK. Here's a comparison video I took, with normal animation speed:

https://user-images.githubusercontent.com/35242550/118390051-ef2e7380-b5e1-11eb-8dc0-59d14c6a293a.mp4

**Comment by RensAlthuis** [comment]
The real issue here is these lines overviewControls:134-L137
https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/overviewControls.js#L135

Overriding that allocation function and removing those lines should fix this particular issue. Although you probably need to subtract the panel height from the height of the box to get a smooth transition.

PS: those lines are also the cause of #1341

**Comment by PHLAK** [comment]
I just installed the latest version from from `master` (ec4e0784ae4a468ed7c5dc68693ae777f5cfe4c5) and am still getting snapping, only now it's snapping _horizontally_ instead of vertically. Here's [a video of the issue](https://youtu.be/xp-cIifTTzE).

**Comment by hrdwrrsk2** [comment]
> I just installed the latest version from from `master` ([ec4e078](https://github.com/home-sweet-gnome/dash-to-panel/commit/ec4e0784ae4a468ed7c5dc68693ae777f5cfe4c5)) and am still getting snapping, only now it's snapping _horizontally_ instead of vertically. Here's a video of the issue.
> 
>  Screencast.from.06-08-2021.08.13.15.PM.mp4 
> If you watch closely it looks like the desktop is being squished horizontally as well which may be the cause of or related to the issue.

the round corners also broken too

**Comment by PHLAK** [comment]
> the round corners also broken too

Yeah, noticed that too. With Intelihide disabled the corners _start_ to round but get cut off.

![Screenshot 2021-06-08 20:46:11](https://user-images.githubusercontent.com/53531/121290130-ece6ce80-c89a-11eb-9d4c-f776469df1d8.png)

**Comment by jderose9** [comment]
@PHLAK I see the chopped bottom corners, but not the horizontal snap. If you made configuration changes since your last restart, can you try to restart GNOME and see if it persists? I did see that in some cases the layout isn't getting reinitialized after d2p settings changes are made.

**Comment by PHLAK** [comment]
@jderose9 I've rebooted completely and the issue persists. Maybe this video shows it better. Notice how the desktop height gets to 100% while there's still space on the left and right then it snaps from there to full width.

https://user-images.githubusercontent.com/53531/121300715-0f351800-c8ac-11eb-9fc7-98b7ce9e43dd.mp4

**Comment by jderose9** [comment]
> @jderose9 I've rebooted completely and the issue persists. Maybe this video shows it better. Notice how the desktop height gets to 100% while there's still space on the left and right then it snaps from there to full width.

Oh, I definitely see it in your video, just not able to reproduce yet.

**Comment by emericg** [comment]
The commit ec4e078 broke the overview for me, I just got a grey screen. I rebooted both gnome and the computer.

**Comment by mbestavros** [comment]
@jderose9 Seconding @emericg's issue; I'm seeing it too when building from the `master` branch. I'm able to reproduce it when I use more than one workspace -- as in, I have two windows open across two separate workspaces (in my case, two different Chrome windows).

**Comment by jderose9** [comment]
@emericg @mbestavros would you mind adding your error logs here?
https://github.com/home-sweet-gnome/dash-to-panel/issues/1350#issuecomment-858150826

**Comment by emericg** [comment]
I'm late for the error log, but the latest commit fix the grey screen, and the transition snap is also gone (which make a huge difference in perceived fluidity).
Also I can't see any problem with rounded corner on my install.
Thanks for your work on this extension!

**Comment by PHLAK** [comment]
@emericg What resolution do you use? My laptop screen is a 4K 16:10 display and I connect it to a 4K 16:9 monitor daily. I notice the issue on both and wonder if that has something to do with it.

**Comment by emericg** [comment]
I've got a single 1440p ultrawide connected to a desktop.

**Comment by philippun1** [comment]
This bug seems to be fixed with 258083f. Tested on Ubuntu and Manjaro.

**Comment by PHLAK** [comment]
Is there anything I can do to help debug this? I'm not afraid to get my hands a bit dirty if needed.

**Comment by j-james** [comment]
I'm also seeing this fixed on Wayland.

**Comment by ganigeorgiev** [comment]
The "chopped" overview out animation seems to occur only when the panel is placed on the top.
This doesn't occur when the panel position is bottom, left or right.

**Comment by Freeplayg** [comment]
Wanted to contribute my recording as well, it's definitely noticeable for me.
Note that I'm on Pop! OS, but disabled the vertical workspaces it includes.

https://user-images.githubusercontent.com/40742947/146615508-7641edcb-134d-4cf1-92cb-78580d4b84af.mp4

**Comment by charlesg99** [comment]
Fixed in v46, thanks
