### ISSUE TITLE
Wallpaper shifts vertically when entering activities view when dash-to-panel is set on the top of the screen in GNOME 40

### ISSUE THREAD

**Issue by jlemonde** [home-sweet-gnome/dash-to-panel#1477]
**Describe the bug**
When pressing the 'super'-key (=windows-key) to access the activities overview, the animation has a bug which makes the wallpaper shift vertically or resize vertically. This effect only occurs if dash-to-panel is set on top of the screen, and the amplitude of the misalignment is proportional to the height of the panel.
This is especially annoying because the top of the screen is the location I really want to have my panel, but right now dash-to-panel wrecks the animation to the activities overview.

https://user-images.githubusercontent.com/30623792/136326353-2720d63e-91be-488d-b84b-e2e4c6583cee.mov

**Linux distribution and version**
Tested on both **Ubuntu 21.10** (two days ahead of release) and **Manjaro GNOME.**

**GNOME Shell version**
gnome-shell versions 40.5 and 40.4 respectively.

**Dash-to-Panel version**
Version 43 in both cases.

**Where was Dash-to-Panel installed from?**
From the GNOME extensions website.

**Additional Info**
This did not happen before I switched to GNOME 40. But this wallpaper resizing animation is new to GNOME 40 anyway, so this is why no adjustment was needed before.

I truly hope this gets fixed soon.

**Comment by Sultech** [comment]
@charlesg99 could you please fix this. It is a very annoying bug.

**Comment by Lilith2208** [comment]
It is a very annoying bug, so I have disabled the animations in my gnome. It happens with all settings that set another height of the background (for transparency and for panel thickness).

**Comment by charlesg99** [comment]
Fixed in v46

**Comment by Sultech** [comment]
@charlesg99 I have just tested and when displaying the panel on all monitors the bug still occurs. However, when displaying the panel on only 1 monitor it is fixed

**Comment by charlesg99** [comment]
Works fine on both my monitors with panels. Testing the latest master on gnome-shell 42.

**Comment by Sultech** [comment]
I just tested latest master and it is working, thanks for fixing the bug
