### ISSUE TITLE
Open applications not showing / closed applications lingering icons

### ISSUE THREAD

**Issue by Philipmikmik** [home-sweet-gnome/dash-to-panel#1544]
When opening an app that doesnt already have its icon in the panel the icon doesnt show at all unless i update the panel in some way. When closing an app the icon lingers as if it were favorited.

Pop!_OS 21.10
GNOME Shell 40.5
Dash-to-Panel v44

Installed from the GNOME extension page

**Comment by jrom99** [comment]
I have a similar problem on Ubuntu 21.10 (GNOME Shell 40.5 and Dash-to-Panel v44, installed from extensions website).

Sometimes Nautilus doesn't have a running indicator, or, if it does, it only shows one window as active. It seems to be specific to Nautilus as far as I've tested, and Meta+Num opens a new Nautilus window.

Example with two windows open and no indicator available
![image](https://user-images.githubusercontent.com/47498278/147604564-0f14513b-c12e-4b54-9143-6bb54bc853f3.png)

Example with two windows open and two indicators available with Extension disabled
![image](https://user-images.githubusercontent.com/47498278/147604664-66168dd6-da02-4ba1-8484-0a82d7cd805e.png)

Example with two windows open and only one indicator available (I don't really know how to replicate it, but the default seems to be no running indicator)
![image](https://user-images.githubusercontent.com/47498278/147604905-5950449d-2247-4f30-b8dd-6bdc93934e7f.png)

Another bug is that after changing panel position from top to left and back, or disabling and re-enabling it, the applications are hidden (toggling the first item "Show favorite applications" is the only way I found that's able to unhide them)
![image](https://user-images.githubusercontent.com/47498278/147604807-8dd367fd-2f7a-46b5-84e0-c9c6cbcc02e0.png)

**Comment by Zachu** [comment]
Same problem keeps me from using this extension.

- When enabling this extension, I have no applications shown in the "Running applications" section.
- Toggling "Show running applications" off and on again gets all apps to show correctly
- Closing the Extensions settings leaves the Extensions icon lingering in the top bar, I'd rather have it leave there since it's no longer running. The running indicators do go away though
- Opening completely new application doesn't show in the menu either
- Once again toggling the "Show running applications" off and on again gets them to show correctly

What I get by running `journalctl /usr/bin/gnome-shell -f -o cat` while opening a new applications that doesn't go into the "Running applications section":
```
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x5e000f8
Can't update stage views actor MetaWindowGroup is on because it needs an allocation.
Can't update stage views actor MetaWindowActorX11 is on because it needs an allocation.
Can't update stage views actor MetaSurfaceActorX11 is on because it needs an allocation.
JS ERROR: TypeError: iconTexture.get_names is not a function
_getIconPixBuf@/home/zachu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js:846:61
_getColorPalette@/home/zachu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js:865:27
_getFocusHighlightColor@/home/zachu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:1089:31
_setIconStyle@/home/zachu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:606:39
_displayProperIndicator@/home/zachu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:703:14
_onFocusAppChanged@/home/zachu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:683:14

JS ERROR: TypeError: iconTexture.get_names is not a function
_getIconPixBuf@/home/zachu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js:846:61
_getColorPalette@/home/zachu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js:865:27
_getFocusHighlightColor@/home/zachu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:1089:31
_setIconStyle@/home/zachu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:606:39
_displayProperIndicator@/home/zachu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:703:14
_onFocusAppChanged@/home/zachu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:683:14

JS ERROR: TypeError: iconTexture.get_names is not a function
_getIconPixBuf@/home/zachu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js:846:61
_getColorPalette@/home/zachu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js:865:27
_getFocusHighlightColor@/home/zachu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:1089:31
_setIconStyle@/home/zachu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:606:39
_displayProperIndicator@/home/zachu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:703:14
_onFocusAppChanged@/home/zachu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:683:14
``

**Comment by Philipmikmik** [comment]
I found a temporary "fix". If you lock and unlock your taskbar the bar refreshes and shows the applications.

**Comment by Zachu** [comment]
That indeed seems to refresh it for me as well. But is that something, or can someone figure out anything, that could be done from CLI? I'd automate it to be done every 5 seconds or something equally dumb =)

**Comment by josefcs** [comment]
@Philipmikmik I also have this problem.
I have tested it with ubuntu 20.04 and 21.10!
The problem also exists with the original panel (dash-to-dock).
So I suspect that the problem must be something deeper underlying, i.e. the system not reporting an update of the running applications correctly?
The problem does not occur on a fresh installation, only a while after usage. I was not able to determine which change caused this behavior.

**Comment by charlesg99** [comment]
Probably related to #1500, also the problem with `iconTexture.get_names` is was fixed a while ago. Thanks!

**Comment by alexdmccabe** [comment]
I'm still seeing this.

Fedora 41
GNOME 47
Dash-to-Panel 68

Should / could this be re-opened, or a new issue created?
