### ISSUE TITLE
Workspace isolation isn't working properly

### ISSUE THREAD

**Issue by MrSnugglesGH** [home-sweet-gnome/dash-to-panel#1610]
Ubuntu 22.04 Beta
Dash to Panel for gnome 42
workspace isolation is 'on' in the settings of dash-to-panel

Just open up any app and then go to Overview. Manually drag the app window to another workspace in the workspace switcher, however remain on the same workspace you opened the app on. Notice how there is no window in the Overview on the workspace you are in, however, there is an indicator in the panel showing that there is an opened app even though the app is on another workspace. Now, move to any other workspace and then go back to the one you started on. After you do that, there will no longer be an indicator in the panel and this is the desired behavior since the app window is now on another workspace. 

I should note that the same buggy behavior with workspace isolation is a problem with dash-to-dock extension, however that extension isn't yet officially ported to gnome 42.

**Comment by charlesg99** [comment]
Thanks! Indeed it wasn't updated correctly, should now work on the master branch!

**Comment by MrSnugglesGH** [comment]
Wow that was fast :D 

Unless I am doing something wrong, it seems that the bug persists for pinned apps. Unpinned apps work as they are supposed to. Pinned apps still behave as I described above.

**Comment by sammdu** [comment]
Looks like this bug is back :(

I am on Pop!_OS 22.04 with GNOME 42. I cannot drag any window to a different workspace using the workspace overview on top. I can only move it to the workspaces beside the current one by dragging it to the left or right. 

This problem goes away when I disable dash-to-panel in Extensions. 

Similar to #766 except that bug emerged in GNOME 3.x

Appreciate your help!

**Comment by zoe-gm** [comment]
Getting the same issue as mentioned above on Ubuntu 22.04 and GOME 42.5. Cannot drag and drop windows to other workspaces from overview. Very inconsistent: if dash to panel is not set on top, everything works fine. Also if I turn on and off some settings (Isolate Worspaces notably), it works again for a couple minutes.
