### ISSUE TITLE
Possible bug causing gnome-shell + mutter segfault

### ISSUE THREAD

**Issue by Slaviusz** [home-sweet-gnome/dash-to-panel#1783]
Switching among opened windows in the taskbar (randomly) triggers mutter segfault + gnome-shell crash:

gnome-shell: v42.5
mutter: v42.5
Dash-to-Panel: v52

```
[17087.349906] gnome-shell[1353]: segfault at 2e1 ip 00007fef5813b375 sp 00007ffcfd946850 error 4 in libmutter-clutter-10.so.0.0.0[7fef5810a000+a3000]
[17087.349916] Code: 5d c3 0f 1f 00 53 48 8b 5f 20 48 8b bb e0 02 00 00 e8 2f 35 fd ff 48 89 83 e0 02 00 00 5b c3 66 0f 1f 44 00 00 53 48 8b 5f 20 <48> 8b bb e0 02 00 00 e8 5f 42 fd ff 48 89 83 e0 02 00 00 5b c3 66
```

Please have a look here, I have described the bug and provided information to gnome/mutter developers.

https://gitlab.gnome.org/GNOME/mutter/-/issues/2475

**Comment by Slaviusz** [comment]
Hello,
  thank you for looking into this. I have not yet tried the fix. I'd need to recompile mutter (hopefully only mutter) but I was not able to reliably reproduce the crash since I changed some of the extension settings in hope to mitigate or remove the crash.
I'll try the fix in the following few days and report back. Thank you for providing the repro steps I hope I'll be able to quickly simulate the situation with and without the patch to confirm.

**Comment by Slaviusz** [comment]
Hi, I figured out how to reproduce the bug now. 

I've enabled some options I had disabled but I was using before. Just to note, I did not have any crashes until now even with the original version since I disabled some options.

The options I have enabled now (which trigger the bug) are:
Behaviour -> Isolate workspaces
Behavior -> Show notification counter badge
Position -> (from Monitor centered to) Centered

I highly suspect the last setting mentioned to be the culprit here, at least in combination with other settings.

I will compile mutter from git now and report back after testing.

**Comment by Slaviusz** [comment]
Hello again,

  with git version of mutter nothing crashed but I see these errors in my jourlnal, can you please have a look and confirm it's related? Thanks you in advance.

dmesg:
```
[  375.645536] gjs[2266]: segfault at 5569bc000000 ip 00007fb495a9cb85 sp 00007ffe7cf86250 error 4 in libc.so.6[7fb495a28000+173000] likely on CPU 10 (core 2, socket 0)
[  375.645550] Code: b1 15 00 a8 04 74 26 48 8b 15 07 a8 15 00 48 8d 04 95 00 00 00 00 48 f7 d8 48 85 d2 48 c7 c2 00 00 00 fc 48 0f 44 c2 48 21 f0 <48> 8b 38 31 d2 e8 11 d1 ff ff 64 89 2b 48 83 c4 18 5b 5d c3 0f 1f
```

journalctl:
```
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <unnamed>[<ClutterActor>:0x55930abebc50] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <panelBox>[<StBoxLayout>:0x55930a8db840] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <unnamed>[<Gjs_dash-to-panel_jderose9_github_com_panel_Panel>:0x55930b7366d0] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <panel>[<Gjs_ui_panel_Panel>:0x55930ae57bf0] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <unnamed>[<StBin>:0x55930bb27870] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <dashtopanelTaskbar>[<Gjs_dash-to-panel_jderose9_github_com_taskbar_TaskbarActor>:0x55930baf54b0] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <dashtopanelScrollview>[<StScrollView>:0x55930bb0af10] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <unnamed>[<StBoxLayout>:0x55930b4f9ef0] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <unnamed>[<Gjs_dash-to-panel_jderose9_github_com_taskbar_TaskbarItemContainer>:0x55930cc1c020] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <unnamed>[<Gjs_dash-to-panel_jderose9_github_com_appIcons_TaskbarAppIcon>:0x55930c1cdea0] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <unnamed>[<StWidget>:0x55930bc34c20] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <unnamed>[<StWidget>:0x55930b199c60] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <unnamed>[<StDrawingArea>:0x55930a822d30] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <unnamed>[<ClutterActor>:0x55930abebc50] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <panelBox>[<StBoxLayout>:0x55930a8db840] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <unnamed>[<Gjs_dash-to-panel_jderose9_github_com_panel_Panel>:0x55930b7366d0] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <panel>[<Gjs_ui_panel_Panel>:0x55930ae57bf0] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <unnamed>[<StBin>:0x55930bb27870] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <dashtopanelTaskbar>[<Gjs_dash-to-panel_jderose9_github_com_taskbar_TaskbarActor>:0x55930baf54b0] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <dashtopanelScrollview>[<StScrollView>:0x55930bb0af10] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <unnamed>[<StBoxLayout>:0x55930b4f9ef0] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <unnamed>[<Gjs_dash-to-panel_jderose9_github_com_taskbar_TaskbarItemContainer>:0x55930cc1c020] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <unnamed>[<Gjs_dash-to-panel_jderose9_github_com_appIcons_TaskbarAppIcon>:0x55930c1cdea0] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <unnamed>[<StWidget>:0x55930bc34c20] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <unnamed>[<StWidget>:0x55930b199c60] is on because it needs an allocation.
okt 23 12:16:36 gentoo gnome-shell[1336]: Can't update stage views actor <unnamed>[<StDrawingArea>:0x55930ff4ec30] is on because it needs an allocation.
okt 23 12:16:44 gentoo gjs[2266]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(),
or remove() vfuncs. Because it would crash the application, it has been blocked.
okt 23 12:16:44 gentoo gjs[2266]: The offending callback was ScaleFormatValueFunc().
okt 23 12:16:44 gentoo org.gnome.Shell.Extensions[2266]: == Stack trace for context 0x5569bc832190 ==
okt 23 12:16:44 gentoo org.gnome.Shell.Extensions[2266]: #0   5569bc878188 i   resource:///org/gnome/Shell/Extensions/js/dbusService.js:186 (19435cfdaa60 @ 257)
okt 23 12:16:44 gentoo org.gnome.Shell.Extensions[2266]: #1   5569bc8780e0 i   resource:///org/gnome/Shell/Extensions/js/main.js:22 (19435cfda470 @ 97)
okt 23 12:16:44 gentoo org.gnome.Shell.Extensions[2266]: #2   5569bc878048 i   resource:///org/gnome/gjs/modules/script/package.js:206 (19435cfcc290 @ 45)
okt 23 12:16:44 gentoo org.gnome.Shell.Extensions[2266]: #3   5569bc877fc0 i   resource:///org/gnome/gjs/modules/script/package.js:190 (19435cfcc240 @ 37)
okt 23 12:16:44 gentoo org.gnome.Shell.Extensions[2266]: #4   5569bc877f30 i   /usr/share/gnome-shell/org.gnome.Shell.Extensions:1 (19435cfcc060 @ 52)
okt 23 12:16:44 gentoo gjs[2266]: Invalid UTF-8 string passed to pango_layout_set_text()
okt 23 12:16:44 gentoo kernel: gjs[2266]: segfault at 5569bc000000 ip 00007fb495a9cb85 sp 00007ffe7cf86250 error 4 in libc.so.6[7fb495a28000+173000] likely on CPU 10 (core 2, socket 0)
okt 23 12:16:44 gentoo kernel: Code: b1 15 00 a8 04 74 26 48 8b 15 07 a8 15 00 48 8d 04 95 00 00 00 00 48 f7 d8 48 85 d2 48 c7 c2 00 00 00 fc 48 0f 44 c2 48 21 f0 <48> 8b 38 31 d2 e8 11 d1 ff ff 64 89 2b 48 83 c4 18 5b 5d c3 0f 1f
okt 23 12:16:44 gentoo systemd[1]: Created slice Slice /system/systemd-coredump.
okt 23 12:16:44 gentoo systemd[1]: Started Process Core Dump (PID 2981/UID 0).
okt 23 12:16:44 gentoo systemd-coredump[2982]: elfutils disabled, parsing ELF objects not supported
okt 23 12:16:44 gentoo systemd-coredump[2982]: [🡕] Process 2266 (gjs) of user 1000 dumped core.
okt 23 12:16:45 gentoo systemd[1]: systemd-coredump@0-2981-0.service: Deactivated successfully.
```

**Comment by Slaviusz** [comment]
Here's the coredump:

https://gist.github.com/Slaviusz/9e42778f31b83e572feecca1b27c005a

**Comment by charlesg99** [comment]
Hello, thanks for testing the mutter patch, glad it "fixes it". The warnings `Can't update stage views actor...` should be resolved if you install dash to panel from master (see 5e3d3974c1b21001bf7e3efb7821f859ddc6f3da). Could you confirm?

Aside from that I can't see anything related to dash to panel. The `ScaleFormatValueFunc` seems related to the settings dialog, so not sure how it fits in.

**Comment by Slaviusz** [comment]
After testing patched mutter + latest dash-to-panel extension grom git I still get segmentation errors in logs but nothing crashes anymore. I might have been also another extension.

I'm attaching the logs for you to confirm.

Thank you in advance.

dmesg
```
okt 23 17:39:07 gentoo gjs[10514]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
okt 23 17:39:07 gentoo org.gnome.Shell.Extensions[10514]: == Stack trace for context 0x55581383a190 ==
okt 23 17:39:07 gentoo org.gnome.Shell.Extensions[10514]: #0   5558138c4608 i   resource:///org/gnome/Shell/Extensions/js/dbusService.js:186 (2e7d2e1daa60 @ 257)
okt 23 17:39:07 gentoo org.gnome.Shell.Extensions[10514]: #1   5558138c4560 i   resource:///org/gnome/Shell/Extensions/js/main.js:22 (2e7d2e1da470 @ 97)
okt 23 17:39:07 gentoo org.gnome.Shell.Extensions[10514]: #2   5558138c44c8 i   resource:///org/gnome/gjs/modules/script/package.js:206 (2e7d2e1cc290 @ 45)
okt 23 17:39:07 gentoo org.gnome.Shell.Extensions[10514]: #3   5558138c4440 i   resource:///org/gnome/gjs/modules/script/package.js:190 (2e7d2e1cc240 @ 37)
okt 23 17:39:07 gentoo org.gnome.Shell.Extensions[10514]: #4   5558138c43b0 i   /usr/share/gnome-shell/org.gnome.Shell.Extensions:1 (2e7d2e1cc060 @ 52)
okt 23 17:39:07 gentoo gjs[10514]: The offending callback was ScaleFormatValueFunc().
okt 23 17:39:07 gentoo kernel: gjs[10514]: segfault at 555810000000 ip 00007f7b5c29cb85 sp 00007ffc97e40710 error 4 in libc.so.6[7f7b5c228000+173000] likely on CPU 14 (core 6, socket 0)
okt 23 17:39:07 gentoo kernel: Code: b1 15 00 a8 04 74 26 48 8b 15 07 a8 15 00 48 8d 04 95 00 00 00 00 48 f7 d8 48 85 d2 48 c7 c2 00 00 00 fc 48 0f 44 c2 48 21 f0 <48> 8b 38 31 d2 e8 11 d1 ff ff 64 89 2b 48 83 c4 18 5b 5d c3 0f 1f
okt 23 17:39:07 gentoo systemd[1]: Started Process Core Dump (PID 15727/UID 0).
okt 23 17:39:07 gentoo systemd-coredump[15728]: elfutils disabled, parsing ELF objects not supported
okt 23 17:39:07 gentoo systemd-coredump[15728]: [🡕] Process 10514 (gjs) of user 1000 dumped core.
okt 23 17:39:07 gentoo systemd[1]: systemd-coredump@7-15727-0.service: Deactivated successfully.
```

crashdump:
https://gist.github.com/Slaviusz/89e49d1a3d9d222c12b3cec0655e861b

**Comment by Slaviusz** [comment]
I guess we can close this issue? I have not encountered it since then.

**Comment by Slaviusz** [comment]
I guess this can be closed. I have upgraded to gnome-shell-43.1 and mutter-43.1 and haven't seen this reocurring. Thank you for your help.
