### ISSUE TITLE
Bug found: conflict when used with "quick close in overview"

### ISSUE THREAD

**Issue by mapleroyal** [home-sweet-gnome/dash-to-panel#1876]
https://extensions.gnome.org/extension/352/middle-click-to-close-in-overview/

When the dash to panel behavior setting is enabled, "click empty space to close overview", then if the user is using the extension "quick close in overview" it causes the overview to escape when you middle click to close an app in the overview.

My suggestions:

- make the feature work with left and/or right clicks, but not middle click, because middle click is what's used to close apps in the overview with that extension (if you aren't familiar with this functionality, middle clicking to close things is a GUI paradigm that's fairly common)
- change the name of the dash to panel setting, because I think what it is actually intended to do is click an empty space to close in the apps menu (I don't know what it's called in gnome, but it's the view that shows when you double press super)

**Comment by charlesg99** [comment]
Should now work correctly with the master branch

**Comment by mapleroyal** [comment]
Any idea when this will be pushed to the gnome extensions website? This is still an issue in 56 (the currently available version from there).
