### ISSUE TITLE
super+shift+n hotkey doesn't activate new instance in 3.32

### ISSUE THREAD

**Issue by treellama** [home-sweet-gnome/dash-to-panel#661]
Typing super+shift+n doesn't open a new instance of favorites any more. I assume due to https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/370

**Comment by charlesg99** [comment]
Hello treellama, please refer to #601, as I believe this the same issue which was fixed on the latest development version. Thanks!

**Comment by orthecreedence** [comment]
Hello! First of all, wow. This extension is incredible. Great work.

Secondly, I think this issue still might be open. On Windows 10, it was very common for me to do `super+shift+<n>` to create a new instance of a window. This doesn't appear to be working in Dash to Panel. Here is my config (if you need it to reproduce anything):

```
[/]
animate-show-apps=false
appicon-margin=6
appicon-padding=6
click-action='TOGGLE-SHOWPREVIEW'
dot-color-1='#5294e2'
dot-color-2='#5294e2'
dot-color-3='#5294e2'
dot-color-4='#5294e2'
dot-color-dominant=false
dot-color-override=false
dot-color-unfocused-1='#5294e2'
dot-color-unfocused-2='#5294e2'
dot-color-unfocused-3='#5294e2'
dot-color-unfocused-4='#5294e2'
dot-color-unfocused-different=false
dot-position='BOTTOM'
dot-size=3
dot-style-focused='METRO'
dot-style-unfocused='METRO'
focus-highlight=true
focus-highlight-color='#eeeeee'
focus-highlight-dominant=true
focus-highlight-opacity=25
hot-keys=true
hotkeys-overlay-combo='TEMPORARILY'
isolate-workspaces=true
location-clock='STATUSRIGHT'
middle-click-action='LAUNCH'
multi-monitors=false
panel-size=42
preview-use-custom-opacity=false
scroll-icon-action='NOTHING'
scroll-panel-action='NOTHING'
secondarymenu-contains-showdetails=false
shift-click-action='MINIMIZE'
shift-middle-click-action='LAUNCH'
shortcut-previews=true
show-activities-button=false
show-running-apps=true
show-show-apps-button=false
show-showdesktop-button=false
show-window-previews=true
show-window-previews-timeout=500
taskbar-position='LEFTPANEL'
window-preview-hide-immediate-click=true
window-preview-show-title=true
window-preview-size=150
window-preview-title-font-color='#dddddd'
```

It could be possible I just configured something wrong, but so far, if an app isn't open and I do `super+<n>` it opens, and I can to `super+<n>` to toggle windows when there are several open for the same app.

Thanks again for the excellent extension.

**Comment by charlesg99** [comment]
Hello orthecreedence! Yes this is a bit convoluted :) To get it to work as you want, you first need to disable the "Show window previews on hotkey" (in the hotkeys options), then you need to set your "Shift-Click Action" to "Launch new instance" (in the Click action options).

The logic is that a hotkey (shift and non shift) is converted to a left click action if "Show window previews on hotkey" is disabled or if there is only 0-1 window(s) of that application, otherwise it cycles the windows using the window previews.

Hope that helps!

**Comment by orthecreedence** [comment]
Thanks, that works! The only one problem now is I can't cycle through open windows using win+n. Ok, actually if I set click action to Cycle then it works, but I don't get previews (which help in figuring out which window I'm cycling to). One thing that might be nice is a "Toggle single / Preview+cycle multiple" option. Admittedly, I'm coming from Win 10 so maybe I'm just stuck on all the shortcuts it had.

I'll keep playing with it. Thanks!

**Comment by charlesg99** [comment]
I suppose we could cycle window previews only on win+n and ignore it if Shift is pressed. Would that work for you?

**Comment by orthecreedence** [comment]
Well, ideally I'd want it to be like Win 10:

- `win+n`
  - if no app exists, launch it
  - if one app exists and is not focused, focus it
  - if one app exists and is focused, unfocus/minimize it
  - if multiple exist, preview and cycle between them
- `shift+win+n`
  - always launches a new instance

I can get *really* close to this by turning on "Show window previews on hotkey" and setting click action to "Toggle single / Preview multiple". Everything from the above list works *except* `shift+win+n`.

> I suppose we could cycle window previews only on win+n and ignore it if Shift is pressed. Would that work for you?

Actually yeah I think that would work great.

**Comment by charlesg99** [comment]
Hey Andrew! As proposed a new instance should now be launched when the Shift key is pressed. This is available on the master branch, could you [install it](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) and let us know what you think? Thanks!

**Comment by orthecreedence** [comment]
Yesss, I think that did it! Thanks so much!
